# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Dropbox/UEIDAQ/projects/UEIDAQ-System

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Dropbox/UEIDAQ/projects/UEIDAQ-System

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Dropbox/UEIDAQ/projects/UEIDAQ-System/CMakeFiles /mnt/d/Dropbox/UEIDAQ/projects/UEIDAQ-System//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Dropbox/UEIDAQ/projects/UEIDAQ-System/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ueipac_app

# Build rule for target.
ueipac_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ueipac_app
.PHONY : ueipac_app

# fast build rule for target.
ueipac_app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/build
.PHONY : ueipac_app/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/main.cpp.s
.PHONY : main.cpp.s

src/daq/DAQFactory.o: src/daq/DAQFactory.cpp.o
.PHONY : src/daq/DAQFactory.o

# target to build an object file
src/daq/DAQFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/daq/DAQFactory.cpp.o
.PHONY : src/daq/DAQFactory.cpp.o

src/daq/DAQFactory.i: src/daq/DAQFactory.cpp.i
.PHONY : src/daq/DAQFactory.i

# target to preprocess a source file
src/daq/DAQFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/daq/DAQFactory.cpp.i
.PHONY : src/daq/DAQFactory.cpp.i

src/daq/DAQFactory.s: src/daq/DAQFactory.cpp.s
.PHONY : src/daq/DAQFactory.s

# target to generate assembly for a file
src/daq/DAQFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/daq/DAQFactory.cpp.s
.PHONY : src/daq/DAQFactory.cpp.s

src/daq/SimDaqDevice.o: src/daq/SimDaqDevice.cpp.o
.PHONY : src/daq/SimDaqDevice.o

# target to build an object file
src/daq/SimDaqDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/daq/SimDaqDevice.cpp.o
.PHONY : src/daq/SimDaqDevice.cpp.o

src/daq/SimDaqDevice.i: src/daq/SimDaqDevice.cpp.i
.PHONY : src/daq/SimDaqDevice.i

# target to preprocess a source file
src/daq/SimDaqDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/daq/SimDaqDevice.cpp.i
.PHONY : src/daq/SimDaqDevice.cpp.i

src/daq/SimDaqDevice.s: src/daq/SimDaqDevice.cpp.s
.PHONY : src/daq/SimDaqDevice.s

# target to generate assembly for a file
src/daq/SimDaqDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/daq/SimDaqDevice.cpp.s
.PHONY : src/daq/SimDaqDevice.cpp.s

src/dsp/Moving_Average.o: src/dsp/Moving_Average.cpp.o
.PHONY : src/dsp/Moving_Average.o

# target to build an object file
src/dsp/Moving_Average.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/dsp/Moving_Average.cpp.o
.PHONY : src/dsp/Moving_Average.cpp.o

src/dsp/Moving_Average.i: src/dsp/Moving_Average.cpp.i
.PHONY : src/dsp/Moving_Average.i

# target to preprocess a source file
src/dsp/Moving_Average.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/dsp/Moving_Average.cpp.i
.PHONY : src/dsp/Moving_Average.cpp.i

src/dsp/Moving_Average.s: src/dsp/Moving_Average.cpp.s
.PHONY : src/dsp/Moving_Average.s

# target to generate assembly for a file
src/dsp/Moving_Average.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/dsp/Moving_Average.cpp.s
.PHONY : src/dsp/Moving_Average.cpp.s

src/net/UdpSender.o: src/net/UdpSender.cpp.o
.PHONY : src/net/UdpSender.o

# target to build an object file
src/net/UdpSender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/net/UdpSender.cpp.o
.PHONY : src/net/UdpSender.cpp.o

src/net/UdpSender.i: src/net/UdpSender.cpp.i
.PHONY : src/net/UdpSender.i

# target to preprocess a source file
src/net/UdpSender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/net/UdpSender.cpp.i
.PHONY : src/net/UdpSender.cpp.i

src/net/UdpSender.s: src/net/UdpSender.cpp.s
.PHONY : src/net/UdpSender.s

# target to generate assembly for a file
src/net/UdpSender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/net/UdpSender.cpp.s
.PHONY : src/net/UdpSender.cpp.s

src/utils/ConfigLoader.o: src/utils/ConfigLoader.cpp.o
.PHONY : src/utils/ConfigLoader.o

# target to build an object file
src/utils/ConfigLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/utils/ConfigLoader.cpp.o
.PHONY : src/utils/ConfigLoader.cpp.o

src/utils/ConfigLoader.i: src/utils/ConfigLoader.cpp.i
.PHONY : src/utils/ConfigLoader.i

# target to preprocess a source file
src/utils/ConfigLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/utils/ConfigLoader.cpp.i
.PHONY : src/utils/ConfigLoader.cpp.i

src/utils/ConfigLoader.s: src/utils/ConfigLoader.cpp.s
.PHONY : src/utils/ConfigLoader.s

# target to generate assembly for a file
src/utils/ConfigLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/utils/ConfigLoader.cpp.s
.PHONY : src/utils/ConfigLoader.cpp.s

src/utils/CsvPacketizer.o: src/utils/CsvPacketizer.cpp.o
.PHONY : src/utils/CsvPacketizer.o

# target to build an object file
src/utils/CsvPacketizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/utils/CsvPacketizer.cpp.o
.PHONY : src/utils/CsvPacketizer.cpp.o

src/utils/CsvPacketizer.i: src/utils/CsvPacketizer.cpp.i
.PHONY : src/utils/CsvPacketizer.i

# target to preprocess a source file
src/utils/CsvPacketizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/utils/CsvPacketizer.cpp.i
.PHONY : src/utils/CsvPacketizer.cpp.i

src/utils/CsvPacketizer.s: src/utils/CsvPacketizer.cpp.s
.PHONY : src/utils/CsvPacketizer.s

# target to generate assembly for a file
src/utils/CsvPacketizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ueipac_app.dir/build.make CMakeFiles/ueipac_app.dir/src/utils/CsvPacketizer.cpp.s
.PHONY : src/utils/CsvPacketizer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ueipac_app"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/daq/DAQFactory.o"
	@echo "... src/daq/DAQFactory.i"
	@echo "... src/daq/DAQFactory.s"
	@echo "... src/daq/SimDaqDevice.o"
	@echo "... src/daq/SimDaqDevice.i"
	@echo "... src/daq/SimDaqDevice.s"
	@echo "... src/dsp/Moving_Average.o"
	@echo "... src/dsp/Moving_Average.i"
	@echo "... src/dsp/Moving_Average.s"
	@echo "... src/net/UdpSender.o"
	@echo "... src/net/UdpSender.i"
	@echo "... src/net/UdpSender.s"
	@echo "... src/utils/ConfigLoader.o"
	@echo "... src/utils/ConfigLoader.i"
	@echo "... src/utils/ConfigLoader.s"
	@echo "... src/utils/CsvPacketizer.o"
	@echo "... src/utils/CsvPacketizer.i"
	@echo "... src/utils/CsvPacketizer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

